<?php
    $url_order = ($this->order == 'ASC') ? 'DESC' : 'ASC';
    $title = 'Traslados';
    $this->headTitle($title);
?>
<div class="uk-card uk-card-default uk-card-hover">
	<div class="uk-card-header" >
		<div class="uk-child-width-1-2@s" uk-grid>
    		<div>
    			<h2><span data-uk-icon="icon: file-text; ratio: 2"></span> <?= $this->escapeHtml($title) ?></h2>	
    		</div>
    		<div>
    			<form action="" method="post">
            		<div class="uk-flex uk-flex-center@s uk-flex-right@m">
            			<div>
            				<label>Fecha Inicial:</label>
            				<input name="fechaInicial" type="date" class="uk-input uk-form-small" value="<?= date('Y-m-d');?>"/>
            			</div>
            			<div>
            				<label>Fecha Final:</label>
            				<input name="fechaFinal" type="date" class="uk-input uk-form-small" value="<?= date('Y-m-d');?>"/>
            			</div>
            			<div>
            				<label>&nbsp;</label>
            				<input type="submit" class="uk-button uk-form-small" value="Filtrar" />
            			</div>
            		</div>
        		</form>
    		</div>
    	</div>
	</div>
	<div class="uk-card-body">
    	<?php if ($this->traslados->count() != 0): ?>
    	<table class="uk-table uk-table-middle uk-table-hover uk-table-striped uk-table-responsive">
    	    <thead>
    	    <tr>
    	        <th>N°</th>
    	        <th>Fecha Traslado</th>   	        
    	        <th>Hora de llegada</th>
    	        <th>Hora de salida</th>
    	        <th>Horas totales</th>
    	        <th>Cliente</th>
    	        <th>Conductor</th>
    	        <th>Vehiculo (Placa)</th>  
    	        <th>-</th>
    	    </tr>
    	    </thead>
    	    <tbody>
    	    <?php foreach ($this->traslados as $traslado) : ?>    
    	    <tr>
    	        <td><?php echo $this->escapeHtml($traslado->cod_traslado); ?></td>
    	        
    	        <?php //var_dump($traslado)?>
    	        
    	        <td><?php echo $this->escapeHtml($traslado->fecha_traslado);?></td> 
    	        
    	        <?php     	        
    	           $hora_llegada = $traslado->hora_llegada;
    	           $hora_salida = $traslado->hora_salida;
    	           $m = new \Moment\Moment($hora_llegada);
    	           $horas = $m->from($hora_salida)->getHours();
    	           
    	        ?>
    	        <td><?php echo $this->escapeHtml($hora_llegada); ?></td>
    	        
    	        <td><?php echo $this->escapeHtml($hora_salida); ?></td>
    	        
    	        <td><?php echo $horas; ?></td>
    	        
    	        <td><strong><?php echo $this->escapeHtml($traslado->Cliente->razon_social);?></strong></td>
    	        
    	        <td><strong><?php echo $this->escapeHtml($traslado->Conductor->nombres . " " . $traslado->Conductor->apellidos);?></strong></td> 
    	        
    	        <td><strong><?php echo $this->escapeHtml($traslado->Vehiculo->placa);?></strong></td>
    	                
    	        <td>
    	        	<a  href="<?php echo $this->url('traslado_adm', [
    	        	    'action'    => 'ver-traslado',
                        'cod_traslado'  => $traslado->cod_traslado,
    	        	    'cod_cliente'  => $traslado->Cliente->cod_cliente,
    	        	    'cod_conductor'  => $traslado->Conductor->cod_conductor,
    	        	    'cod_vehiculo'  => $traslado->Vehiculo->cod_vehiculo	        	    
    				]); ?>" class="uk-button uk-button-primary uk-button-small">Ver traslado</a>
    				
    				
    			</td>
    	    </tr>
    	    <?php endforeach; ?>
    	    </tbody> 
    	</table>
    	
    	<?php echo $this->paginationControl($this->traslados, 'Sliding', 'paginator', array('route' => 'traslado', 'action' => 'ver-traslados', 'orderby' => $this->orderby, 'order' => $order));?>
    	
    	<?php else: ?>
    		<h2>Aún no has realizado ningún traslado.</h2>
    		<p><a class="uk-button uk-button-primary" href="<?= $this->url('traslado', ['action' => 'nuevo-traslado']) ?>">
    			Click aquí para realizar un nuevo traslado.
    		</a></p>
    	<?php endif;?>
	</div>	
</div>
	


