
<a href="<?php echo $this->url("conductor"); ?>" class="uk-button uk-button-link uk-button-small">
	<span data-uk-icon="icon: reply"></span> Volver
</a>

<div class="uk-card uk-card-default uk-card-small uk-card-hover">
<div class="uk-card-header">
	<h3><?php echo $this->text;?> Conductor</h3>
</div>
<div class="uk-card-body">
	<?php if ($this->action != "eliminar-conductor"): ?>	
		<?php
        	$form = $this->form;
        	$form->setAttribute('action', $this->url('conductor', array('action' => $this->action)));
        	$form->setAttribute('class', 'uk-form-horizontal');
        	$form->prepare();
        	
        	$helper = $this->formElementErrors();
        	$helper->setMessageOpenFormat('<div class="uk-alert uk-alert-danger">');
        	$helper->setMessageSeparatorString('</div><div class="uk-alert uk-alert-danger">');
        	$helper->setMessageCloseString('</div>');
        ?>
		
		<?php echo $this->form()->openTag($form);?>			
			<?php echo $this->formHidden($form->get('cod_conductor')); ?>				
			
			<div class="uk-margin">
				<?php echo $this->formLabel($form->get('nombres')) ?>
				<div class="uk-form-controls">			
    				<?php echo $this->formInput($form->get('nombres')); ?>
    				<?php echo $helper->render($form->get('nombres'));?>
				</div>
			</div>
			
			<div class="uk-margin">
				<?php echo $this->formLabel($form->get('apellidos')) ?>
				<div class="uk-form-controls">
					<?php echo $this->formInput($form->get('apellidos')); ?>
					<?php echo $helper->render($form->get('apellidos'));?>
				</div>
			</div>
			
			<div class="uk-margin">
				<?php echo $this->formLabel($form->get('numero_licencia')) ?>
				<div class="uk-form-controls">
					<?php echo $this->formInput($form->get('numero_licencia')); ?>
					<?php echo $helper->render($form->get('numero_licencia'));?>
				</div>
			</div>		
			
			<div class="uk-margin">
				<div class="">
					<?php echo $this->formInput($form->get('guardar')); ?>
				</div>
			</div>		
		<?php echo $this->form()->closeTag($form);?>
	<?php else: ?>
		 <h3>¿Esta seguro que desea eliminar el conductor: <strong><?php echo $this->escapeHtml($this->Conductor->nombres);?></strong>?</h3>

         <p class="uk-text-danger">La eliminación es definitiva e irreversible</p>
         
         <form action="<?php echo $this->url('conductor', array('action' => 'eliminar-conductor')); ?>" method="post">
        
        	 <input type="hidden" name="cod_conductor" value="<?php echo (int) $this->Conductor->cod_conductor; ?>" />
        	 <input type="hidden" name="nombres" value="<?php echo $this->Conductor->nombres; ?>" />
        	 <input type="submit" name="eliminar" value="si" class="uk-button uk-button-secondary"/>
        	 <input type="submit" name="eliminar" value="no" class="uk-button uk-button-defalut"/>
        
         </form>
	<?php endif; ?>
</div>
</div>
