<?php
    $url_order = ($this->order == 'ASC') ? 'DESC' : 'ASC';
    $title = 'Conductores';
    $this->headTitle($title);
?>

<div class="uk-card uk-card-default uk-card-small uk-card-hover">
<div class="uk-card-header">
	<h2><span data-uk-icon="icon: location; ratio: 2"></span><?= $this->escapeHtml($title) ?></h2>	
</div>
<div class="uk-card-body">

	<a href="<?php echo $this->url("conductor", array('action' => 'agregar-conductor')); ?>" class="uk-button uk-button-add uk-button-small"><span data-uk-icon="icon: plus"></span>Agregar</a>
    
    <table class="uk-table uk-table-hover uk-table-striped">
        <thead>
        <tr>
            <th>Código</th>
            <th>Nombres</th>	        
            <th>Apellidos</th>
            <th>Número de licencia</th>
            <th>-</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($this->conductores as $conductor): ?>    
        <tr>
            <td><?= $this->escapeHtml($conductor->cod_conductor); ?></td>        
            
            <td><?php echo $this->escapeHtml($conductor->nombres);?></td>      
            
            <td><?php echo $this->escapeHtml($conductor->apellidos);?></td>
            
            <td><?php echo $this->escapeHtml($conductor->numero_licencia);?></td>
            
            <td>
            	<a href="<?php echo $this->url('conductor', [
            	    'action'    => 'editar-conductor',
            	    'cod_conductor'  => $conductor->cod_conductor
    			]); ?>" class="uk-button uk-button-edit uk-button-small"><span data-uk-icon="icon: pencil"></span>Editar</a>
    			
    			<a href="<?php echo $this->url('conductor', [
            	    'action'    => 'eliminar-conductor',                
    			    'cod_conductor'  => $conductor->cod_conductor
    			]); ?>" class="uk-button uk-button-delete uk-button-small"><span data-uk-icon="icon: trash"></span>Eliminar</a>
    		</td>
        </tr>
        <?php endforeach; ?>
        </tbody> 
    </table>
    
    <?php echo $this->paginationControl($this->conductores, 'Sliding', 'paginator', array('route' => 'conductor', 'action' => 'index', 'orderby' => $this->orderby, 'order' => $order));?>
 
</div>
</div>